require_relative '../person'
require_relative '../student'
require_relative '../book'
require_relative '../capitalize_decorator'
require_relative '../trimmer_decorator'
require_relative '../rental'
require_relative '../teacher'
